---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
spec:
  strategy:
    type: Recreate
    rollingUpdate: null   
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
    spec:
      containers:
      - name: {{ .Values.name}}
        image: german2404/counter:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
           path: /health
           port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: {{ .Values.name}}

  
---
apiVersion: v1  
kind: Service
metadata:
  name: redisapp
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

