---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: german2404/counter:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
	livenessProbe:
          httpGet:
           path: /health
           port: 8000
         initialDelaySeconds: 5
         periodSeconds: 5
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: pythonbalancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: python
---
apiVersion: v1  
kind: Service
metadata:
  name: redisapp
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

